auth:
  replicas: 4
  image: vero026/auth-service
  tag: latest
  port: 4000

mongo:
  replicas: 3
  image: mongo
  tag: latest
  port: 27017

nginx:
  replicas: 2
  image: vero026/nginx-app
  tag: latest
  port: 80
  nodePort: 30007

ingress:
  host: taskmanager.local