apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: "{{ .Values.auth.image }}:{{ .Values.auth.tag }}"
        
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: auth-config