apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image }}:{{ .Values.mongo.tag }}"
        ports:
        - containerPort: {{ .Values.mongo.port }}